### ISSUE TITLE
The characteristic you write is person specific

### ISSUE THREAD

**Issue by simon6162** [ec1oud/qt-ble-weightscale#1]
Thanks for the code, I've been using it to link my scales into fitbit, one day I'll post the code, for now

```
        case QLowEnergyCharacteristic::Write:
            // TODO figure out if this is the preferences or what.  But merely subscribing for notifications
            // without writing to this characteristic seems not to be enough.
m_service->writeCharacteristic(characteristic, QByteArray::fromHex("fe010100aa2d0285"));
```
This characteristic tells the scales how to process its readings and who is selected in the app. So you need to set it before trying to read back the data as you have now. This displays the p1, p2 etc and chooses the display units. Also to calculate the body fat etc, it needs your age height sex and activity level. 

Assuming you are User 1 on your scales, Male, a low exerciser, 170 cm tall, 45 years old and report your weight in lbs then I believe this is the definition of the characteristic. 

TT = the header =0xfe                           
UI = user id (p1=0x01, p2=0x02 etc)                            
SS = Sex ( male = 0x01, female = 0x00)
EE = Exercise Level (0x00=ordinary, 0x01=amet, 0x02=professional)
HH = height in cm
AA = age in years (the app does this badly just on the year, form the look of it)
UU = Display units (04=st, lbs, 1=kg, 2=lbs)
CC = Checksum (UI^SS^EE^HH^AA^UU) - xor of the data

```
                    TT UI SS EE HH AA UU CC
1 Attribute Data: 0xfe 01 01 00 aa 2d 02 85
```

**Comment by ec1oud** [comment]
Thanks for the info!  I procrastinated because this means user-specific settings are needed; but that is now done in https://github.com/ec1oud/trayble/commit/3ad3539a4a7865aef4d10d6560a3ee236a41647f
